### ISSUE TITLE
Working with non-AbstractArray types

### ISSUE THREAD

**Issue by MasonProtter** [JuliaFolds2/ChunkSplitters.jl#21]
I know it'd be a lot of work for ChunkSplitters to systematically try to support non-AbstractArray types, but it'd be good if there was some docs guidance for other people to try and implement methods so that their types can be supported as well.

**Comment by lmiq** [comment]
(actually in terms of implementation I think the error messages would be better if they failed at those functions of the interface). I think I'lll release that right away.

**Comment by lmiq** [comment]
It is done in the 2.2.0 branch: https://github.com/m3g/ChunkSplitters.jl/tree/release-2.2.0

If you don't have any suggestion, I'll release it (it will make a contract relative to the interface, so if you find that something can be even further simplified, let me know).

The only downside of this is that now `chunks` works on scalars, which I find a bad thing, but that's just how Julia is.

**Comment by MasonProtter** [comment]
Oops sorry I missed this @lmiq! I think I'm in favour of this. In particular, this is nice because it lets you take chunks of chunks!

**Comment by lmiq** [comment]
Pinging @carstenbauer again here, maybe he missed it to. If you all are ok, I can release that asap.

**Comment by MasonProtter** [comment]
One thing we could do if you want better error messages is do something like
```
is_chunkable(x) = false
is_chunkable(x::AbstractArray) = true
is_chunkable(x::Chunk) = true
is_chunkable(x::Tuple) = true

function chunks(x; n, split=:batch)
    if !is_chunkable(x)
        error("something informative")
    end
end
```

**Comment by carstenbauer** [comment]
Just took a quick look and LGTM. Apart from Mason's suggestion I only have a minor stylistic comment: I would probably rename the function argument / field name `array` to `data` or whatever because it might not be an array after all.

**Comment by lmiq** [comment]
Thanks! Yesterday I wasn't able to do anything. But all is fine!
