### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by carstenbauer** [JuliaFolds2/ChunkSplitters.jl#47]
Given the significant changes in #46, the fact that there is lots of legacy code around, and the discussion in #25 I wonder whether we should simply aim for making a breaking 3.0 release soon.

A summary of the new API / changes that need to be made (likely incomplete and maybe some points are still up for debate):

* [ ] new function `chunk(x; ...)` that returns an iterator that delivers the chunks, i.e. views into `x`. (We choose `chunk`, singular, here to indicate the verb form `to chunk`. This is to be in line with `enumerate`, `zip`, and co.)
* [ ] rename `chunks(x; ...)` to `chunk_indices(x; ...)` and make the latter return an iterator that delivers the indices (of `x`) for each chunk.
* [ ] iterator names: `Chunk` (returned by `chunk`) and `ChunkIndices` (returned by `chunk_indices`). This is in line with `Base.Iterators.Enumerate` (returned by `enumerate`), `Base.Pairs` (returned by `pairs`), and `Base.Iterators.Zip` (returned by `zip`)
* [ ] drop the legacy API that relies on positional arguments
* [ ] drop the `Symbol` option for `split`. While it is slightly more convenient, it can be less efficient and it doesn't make much sense to have two ways to do the same thing.
* [ ] make `getchunk` internal (not public API anymore)

What I think might make sense but I'm unsure about / not sure it's worth it:

* Should we rename `BatchSplit` to `ContiguousSplit`? The latter seems to communicate the critical point more clearly: the resulting chunks hold contiguous data.
* I don't like that we use "chunk" on the one hand and "split" on the other hand. Why two terms for the same thing? Perhaps something like `chunk(x; n=4, strategy=Contiguous())` or something less verbose makes more sense as it gets rid of "split" terminology entirely?

**Comment by carstenbauer** [comment]
cc @lmiq

**Comment by fredrikekre** [comment]
Something else to consider: Perhaps the `size` and `minchunksize` kwargs should be symmetric (either `size` and `minsize` or `chunksize` and `minchunksize` (or `chunk_size` and `min_chunk_size`))?

**Comment by lmiq** [comment]
I would go for `minsize, or `sizemin` maybe? (adding `chunk` again seems too repetitive (`chunks(itr; chunksize=5)`).

**Comment by fredrikekre** [comment]
I don't mind that it is explicit. OhMyThreads uses `chunksize` and `nchunks` (although there you don't pass it to the `chunks` function so not as obvious).

`n` -> `nchunks` is perhaps also something to consider.

**Comment by lmiq** [comment]
I think here those are unnecessarily verbose. It is not the same context as in OhMyThreads. 

(I have the feeling that the parameter was called `nchunks` before, and we ended up with `n`). 

Most times the `chunks` function is used as part of a `for` loop, and having long names makes the code too long.

**Comment by carstenbauer** [comment]
We should try to keep keyword argument names short, if possible. The downside of just `n=3` is that it isn't descriptive at all. From this POV, something like `chunks(x; count=3)` could be something worth considering. (I also thought of `chunks(x; length=3)` but that's confusing because we also have `size` with a different meaning).

**Comment by carstenbauer** [comment]
(I've made the change `minchunksize` -> `minsize` in #48)
